### ISSUE TITLE
Find better way of passing env variables to django apps running in docker images

### ISSUE THREAD

**Issue by dirkcuys** [p2pu/marvin#6]
Currently it looks like this which is hard to maintain and error prone

```yaml
    env:
      VIRTUAL_HOST: "{{LEARNINGCIRCLES.DOMAIN}}"
      LETSENCRYPT_HOST: "{{LEARNINGCIRCLES.DOMAIN}}"
      LETSENCRYPT_EMAIL: "admin@p2pu.org"
      DOMAIN: "{{LEARNINGCIRCLES.DOMAIN}}"
      DATABASE_URL: "postgres://{{ LEARNINGCIRCLES.DB_USER }}:{{ LEARNINGCIRCLES.DB_PASSWORD }}@postgres:5432/{{LEARNINGCIRCLES.DB_NAME}}"
      ADMIN_EMAIL: "{{LEARNINGCIRCLES.ADMIN_EMAIL}}"
      SECRET_KEY: "{{LEARNINGCIRCLES.SECRET_KEY}}"
      EMAIL_HOST: "{{LEARNINGCIRCLES.EMAIL_HOST}}"
      EMAIL_HOST_USER: "{{LEARNINGCIRCLES.EMAIL_HOST_USER}}"
      EMAIL_HOST_PASSWORD: "{{LEARNINGCIRCLES.EMAIL_HOST_PASSWORD}}"
      DEFAULT_FROM_EMAIL: "{{LEARNINGCIRCLES.DEFAULT_FROM_EMAIL}}"
      TWILIO_ACCOUNT_SID: "{{LEARNINGCIRCLES.TWILIO_ACCOUNT_SID}}"
      TWILIO_AUTH_TOKEN: "{{LEARNINGCIRCLES.TWILIO_AUTH_TOKEN}}"
      TWILIO_NUMBER: "{{LEARNINGCIRCLES.TWILIO_NUMBER}}"
      BROKER_URL: "amqp://guest:guest@rabbitmq//"
      BACKUP_DIR: "{{LEARNINGCIRCLES.BACKUP_DIR}}"
      BACKUP_AWS_ACCESS_KEY_ID: "{{LEARNINGCIRCLES.BACKUP_AWS_ACCESS_KEY_ID}}"
      BACKUP_AWS_SECRET_ACCESS_KEY: "{{LEARNINGCIRCLES.BACKUP_AWS_SECRET_ACCESS_KEY}}"
      BACKUP_AWS_STORAGE_BUCKET_NAME: "{{LEARNINGCIRCLES.BACKUP_AWS_STORAGE_BUCKET_NAME}}"
      BACKUP_AWS_KEY_PREFIX: "{{LEARNINGCIRCLES.BACKUP_AWS_KEY_PREFIX}}"
      GA_TRACKING_ID: "{{LEARNINGCIRCLES.GA_TRACKING_ID}}" 
```
